services:
  app:
    build:
      context: ./docker/python
      args:
        - UID=1000
        - GID=1000
        - USERNAME=django
        - GROUPNAME=django
    container_name: django
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./src:/workspace
    ports:
      - 8001:8001
    # depends_on:
    #   - db
    environment:
      - WATCHFILES_FORCE_POLLING=true

#   db:
#     build: ./docker/mysql
#     container_name: mysql
#     platform: linux/amd64
#     environment:
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#     volumes:
#       - db-store:/var/lib/mysql
#       - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#     ports:
#       - 3306:3306

# volumes:
#   db-store:
